version: '3.8'

services:
  # User Service
  user-service:
    build: 
      context: ./user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb+srv://root:root@microservices.6vjersb.mongodb.net/users
      - JWT_SECRET=your_jwt_secret_key
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    volumes:
      - ./user-service:/app
      - ./shared:/app/shared
      - /app/node_modules

  # Product Service
  product-service:
    build:
      context: ./product-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGODB_URI=mongodb+srv://root:root@microservices.6vjersb.mongodb.net/products
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    volumes:
      - ./product-service:/app
      - ./shared:/app/shared
      - /app/node_modules

  # Order Service
  order-service:
    build:
      context: ./order-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - MONGODB_URI=mongodb+srv://root:root@microservices.6vjersb.mongodb.net/orders
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    volumes:
      - ./order-service:/app
      - ./shared:/app/shared
      - /app/node_modules

  # Payment Service
  payment-service:
    build:
      context: ./payment-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - MONGODB_URI=mongodb+srv://root:root@microservices.6vjersb.mongodb.net/payments
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    volumes:
      - ./payment-service:/app
      - ./shared:/app/shared
      - /app/node_modules

  # Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5173"
    environment:
      - VITE_API_USER_URL=http://localhost:3001
      - VITE_API_PRODUCT_URL=http://localhost:3002
      - VITE_API_ORDER_URL=http://localhost:3003
      - VITE_API_PAYMENT_URL=http://localhost:3004
    depends_on:
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
      payment-service:
        condition: service_started
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data: 